#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCMS_Local.LTSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cbhis")]
	public partial class DCCbhisDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBM(BM instance);
    partial void UpdateBM(BM instance);
    partial void DeleteBM(BM instance);
    partial void InsertZG(ZG instance);
    partial void UpdateZG(ZG instance);
    partial void DeleteZG(ZG instance);
    partial void InsertZYBR(ZYBR instance);
    partial void UpdateZYBR(ZYBR instance);
    partial void DeleteZYBR(ZYBR instance);
    partial void InsertRY(RY instance);
    partial void UpdateRY(RY instance);
    partial void DeleteRY(RY instance);
    partial void InsertBASY(BASY instance);
    partial void UpdateBASY(BASY instance);
    partial void DeleteBASY(BASY instance);
    #endregion
		
		public DCCbhisDataContext() : 
				base(global::NCMS_Local.Properties.Settings.Default.cbhisConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCCbhisDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCCbhisDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCCbhisDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCCbhisDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BM> BM
		{
			get
			{
				return this.GetTable<BM>();
			}
		}
		
		public System.Data.Linq.Table<ZG> ZG
		{
			get
			{
				return this.GetTable<ZG>();
			}
		}
		
		public System.Data.Linq.Table<ZYBR> ZYBR
		{
			get
			{
				return this.GetTable<ZYBR>();
			}
		}
		
		public System.Data.Linq.Table<RY> RY
		{
			get
			{
				return this.GetTable<RY>();
			}
		}
		
		public System.Data.Linq.Table<BASY> BASY
		{
			get
			{
				return this.GetTable<BASY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BM")]
	public partial class BM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _BMDM;
		
		private string _BMMC;
		
		private byte _BMLBDM;
		
		private string _PYM;
		
		private short _YJBMDM;
		
		private System.Nullable<short> _KSLBDM;
		
		private string _KS_YBBM;
		
		private System.Nullable<bool> _SFCW;
		
		private System.Nullable<bool> _SFKY;
		
		private string _bz;
		
		private System.Nullable<byte> _KFLX;
		
		private System.Nullable<bool> _IsMZ;
		
		private System.Nullable<bool> _IsZY;
		
		private System.Nullable<decimal> _YPZB;
		
		private string _wbm;
		
		private System.Nullable<byte> _ISZZ;
		
		private EntitySet<ZG> _ZG;
		
		private EntitySet<RY> _RY;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBMDMChanging(short value);
    partial void OnBMDMChanged();
    partial void OnBMMCChanging(string value);
    partial void OnBMMCChanged();
    partial void OnBMLBDMChanging(byte value);
    partial void OnBMLBDMChanged();
    partial void OnPYMChanging(string value);
    partial void OnPYMChanged();
    partial void OnYJBMDMChanging(short value);
    partial void OnYJBMDMChanged();
    partial void OnKSLBDMChanging(System.Nullable<short> value);
    partial void OnKSLBDMChanged();
    partial void OnKS_YBBMChanging(string value);
    partial void OnKS_YBBMChanged();
    partial void OnSFCWChanging(System.Nullable<bool> value);
    partial void OnSFCWChanged();
    partial void OnSFKYChanging(System.Nullable<bool> value);
    partial void OnSFKYChanged();
    partial void OnbzChanging(string value);
    partial void OnbzChanged();
    partial void OnKFLXChanging(System.Nullable<byte> value);
    partial void OnKFLXChanged();
    partial void OnIsMZChanging(System.Nullable<bool> value);
    partial void OnIsMZChanged();
    partial void OnIsZYChanging(System.Nullable<bool> value);
    partial void OnIsZYChanged();
    partial void OnYPZBChanging(System.Nullable<decimal> value);
    partial void OnYPZBChanged();
    partial void OnwbmChanging(string value);
    partial void OnwbmChanged();
    partial void OnISZZChanging(System.Nullable<byte> value);
    partial void OnISZZChanged();
    #endregion
		
		public BM()
		{
			this._ZG = new EntitySet<ZG>(new Action<ZG>(this.attach_ZG), new Action<ZG>(this.detach_ZG));
			this._RY = new EntitySet<RY>(new Action<RY>(this.attach_RY), new Action<RY>(this.detach_RY));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMDM", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short BMDM
		{
			get
			{
				return this._BMDM;
			}
			set
			{
				if ((this._BMDM != value))
				{
					this.OnBMDMChanging(value);
					this.SendPropertyChanging();
					this._BMDM = value;
					this.SendPropertyChanged("BMDM");
					this.OnBMDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMMC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string BMMC
		{
			get
			{
				return this._BMMC;
			}
			set
			{
				if ((this._BMMC != value))
				{
					this.OnBMMCChanging(value);
					this.SendPropertyChanging();
					this._BMMC = value;
					this.SendPropertyChanged("BMMC");
					this.OnBMMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMLBDM", DbType="TinyInt NOT NULL")]
		public byte BMLBDM
		{
			get
			{
				return this._BMLBDM;
			}
			set
			{
				if ((this._BMLBDM != value))
				{
					this.OnBMLBDMChanging(value);
					this.SendPropertyChanging();
					this._BMLBDM = value;
					this.SendPropertyChanged("BMLBDM");
					this.OnBMLBDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PYM", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PYM
		{
			get
			{
				return this._PYM;
			}
			set
			{
				if ((this._PYM != value))
				{
					this.OnPYMChanging(value);
					this.SendPropertyChanging();
					this._PYM = value;
					this.SendPropertyChanged("PYM");
					this.OnPYMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YJBMDM", DbType="SmallInt NOT NULL")]
		public short YJBMDM
		{
			get
			{
				return this._YJBMDM;
			}
			set
			{
				if ((this._YJBMDM != value))
				{
					this.OnYJBMDMChanging(value);
					this.SendPropertyChanging();
					this._YJBMDM = value;
					this.SendPropertyChanged("YJBMDM");
					this.OnYJBMDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KSLBDM", DbType="SmallInt")]
		public System.Nullable<short> KSLBDM
		{
			get
			{
				return this._KSLBDM;
			}
			set
			{
				if ((this._KSLBDM != value))
				{
					this.OnKSLBDMChanging(value);
					this.SendPropertyChanging();
					this._KSLBDM = value;
					this.SendPropertyChanged("KSLBDM");
					this.OnKSLBDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KS_YBBM", DbType="VarChar(30)")]
		public string KS_YBBM
		{
			get
			{
				return this._KS_YBBM;
			}
			set
			{
				if ((this._KS_YBBM != value))
				{
					this.OnKS_YBBMChanging(value);
					this.SendPropertyChanging();
					this._KS_YBBM = value;
					this.SendPropertyChanged("KS_YBBM");
					this.OnKS_YBBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFCW", DbType="Bit")]
		public System.Nullable<bool> SFCW
		{
			get
			{
				return this._SFCW;
			}
			set
			{
				if ((this._SFCW != value))
				{
					this.OnSFCWChanging(value);
					this.SendPropertyChanging();
					this._SFCW = value;
					this.SendPropertyChanged("SFCW");
					this.OnSFCWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFKY", DbType="Bit")]
		public System.Nullable<bool> SFKY
		{
			get
			{
				return this._SFKY;
			}
			set
			{
				if ((this._SFKY != value))
				{
					this.OnSFKYChanging(value);
					this.SendPropertyChanging();
					this._SFKY = value;
					this.SendPropertyChanged("SFKY");
					this.OnSFKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bz", DbType="VarChar(200)")]
		public string bz
		{
			get
			{
				return this._bz;
			}
			set
			{
				if ((this._bz != value))
				{
					this.OnbzChanging(value);
					this.SendPropertyChanging();
					this._bz = value;
					this.SendPropertyChanged("bz");
					this.OnbzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KFLX", DbType="TinyInt")]
		public System.Nullable<byte> KFLX
		{
			get
			{
				return this._KFLX;
			}
			set
			{
				if ((this._KFLX != value))
				{
					this.OnKFLXChanging(value);
					this.SendPropertyChanging();
					this._KFLX = value;
					this.SendPropertyChanged("KFLX");
					this.OnKFLXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMZ", DbType="Bit")]
		public System.Nullable<bool> IsMZ
		{
			get
			{
				return this._IsMZ;
			}
			set
			{
				if ((this._IsMZ != value))
				{
					this.OnIsMZChanging(value);
					this.SendPropertyChanging();
					this._IsMZ = value;
					this.SendPropertyChanged("IsMZ");
					this.OnIsMZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsZY", DbType="Bit")]
		public System.Nullable<bool> IsZY
		{
			get
			{
				return this._IsZY;
			}
			set
			{
				if ((this._IsZY != value))
				{
					this.OnIsZYChanging(value);
					this.SendPropertyChanging();
					this._IsZY = value;
					this.SendPropertyChanged("IsZY");
					this.OnIsZYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YPZB", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> YPZB
		{
			get
			{
				return this._YPZB;
			}
			set
			{
				if ((this._YPZB != value))
				{
					this.OnYPZBChanging(value);
					this.SendPropertyChanging();
					this._YPZB = value;
					this.SendPropertyChanged("YPZB");
					this.OnYPZBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wbm", DbType="VarChar(10)")]
		public string wbm
		{
			get
			{
				return this._wbm;
			}
			set
			{
				if ((this._wbm != value))
				{
					this.OnwbmChanging(value);
					this.SendPropertyChanging();
					this._wbm = value;
					this.SendPropertyChanged("wbm");
					this.OnwbmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISZZ", DbType="TinyInt")]
		public System.Nullable<byte> ISZZ
		{
			get
			{
				return this._ISZZ;
			}
			set
			{
				if ((this._ISZZ != value))
				{
					this.OnISZZChanging(value);
					this.SendPropertyChanging();
					this._ISZZ = value;
					this.SendPropertyChanged("ISZZ");
					this.OnISZZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BM_ZG", Storage="_ZG", ThisKey="BMDM", OtherKey="BMDM")]
		public EntitySet<ZG> ZG
		{
			get
			{
				return this._ZG;
			}
			set
			{
				this._ZG.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BM_RY", Storage="_RY", ThisKey="BMDM", OtherKey="RYKS")]
		public EntitySet<RY> RY
		{
			get
			{
				return this._RY;
			}
			set
			{
				this._RY.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ZG(ZG entity)
		{
			this.SendPropertyChanging();
			entity.BM = this;
		}
		
		private void detach_ZG(ZG entity)
		{
			this.SendPropertyChanging();
			entity.BM = null;
		}
		
		private void attach_RY(RY entity)
		{
			this.SendPropertyChanging();
			entity.BM = this;
		}
		
		private void detach_RY(RY entity)
		{
			this.SendPropertyChanging();
			entity.BM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZG")]
	public partial class ZG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _ZGDM;
		
		private string _ZGXM;
		
		private string _PYM;
		
		private string _XB;
		
		private System.Nullable<System.DateTime> _CSRQ;
		
		private System.Nullable<short> _ZCDM;
		
		private string _ZYZH;
		
		private System.Nullable<byte> _ZGLBDM;
		
		private string _HY;
		
		private string _ZZMM;
		
		private string _MM;
		
		private string _SFZH;
		
		private System.Nullable<short> _BMDM;
		
		private string _GRBH;
		
		private string _LXDH;
		
		private string _XL;
		
		private string _JG;
		
		private System.Nullable<bool> _SFJY;
		
		private System.Data.Linq.Binary _IMAGE;
		
		private string _BZ;
		
		private string _DZ;
		
		private string _WBM;
		
		private EntityRef<BM> _BM;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZGDMChanging(short value);
    partial void OnZGDMChanged();
    partial void OnZGXMChanging(string value);
    partial void OnZGXMChanged();
    partial void OnPYMChanging(string value);
    partial void OnPYMChanged();
    partial void OnXBChanging(string value);
    partial void OnXBChanged();
    partial void OnCSRQChanging(System.Nullable<System.DateTime> value);
    partial void OnCSRQChanged();
    partial void OnZCDMChanging(System.Nullable<short> value);
    partial void OnZCDMChanged();
    partial void OnZYZHChanging(string value);
    partial void OnZYZHChanged();
    partial void OnZGLBDMChanging(System.Nullable<byte> value);
    partial void OnZGLBDMChanged();
    partial void OnHYChanging(string value);
    partial void OnHYChanged();
    partial void OnZZMMChanging(string value);
    partial void OnZZMMChanged();
    partial void OnMMChanging(string value);
    partial void OnMMChanged();
    partial void OnSFZHChanging(string value);
    partial void OnSFZHChanged();
    partial void OnBMDMChanging(System.Nullable<short> value);
    partial void OnBMDMChanged();
    partial void OnGRBHChanging(string value);
    partial void OnGRBHChanged();
    partial void OnLXDHChanging(string value);
    partial void OnLXDHChanged();
    partial void OnXLChanging(string value);
    partial void OnXLChanged();
    partial void OnJGChanging(string value);
    partial void OnJGChanged();
    partial void OnSFJYChanging(System.Nullable<bool> value);
    partial void OnSFJYChanged();
    partial void OnIMAGEChanging(System.Data.Linq.Binary value);
    partial void OnIMAGEChanged();
    partial void OnBZChanging(string value);
    partial void OnBZChanged();
    partial void OnDZChanging(string value);
    partial void OnDZChanged();
    partial void OnWBMChanging(string value);
    partial void OnWBMChanged();
    #endregion
		
		public ZG()
		{
			this._BM = default(EntityRef<BM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZGDM", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short ZGDM
		{
			get
			{
				return this._ZGDM;
			}
			set
			{
				if ((this._ZGDM != value))
				{
					this.OnZGDMChanging(value);
					this.SendPropertyChanging();
					this._ZGDM = value;
					this.SendPropertyChanged("ZGDM");
					this.OnZGDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZGXM", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ZGXM
		{
			get
			{
				return this._ZGXM;
			}
			set
			{
				if ((this._ZGXM != value))
				{
					this.OnZGXMChanging(value);
					this.SendPropertyChanging();
					this._ZGXM = value;
					this.SendPropertyChanged("ZGXM");
					this.OnZGXMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PYM", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PYM
		{
			get
			{
				return this._PYM;
			}
			set
			{
				if ((this._PYM != value))
				{
					this.OnPYMChanging(value);
					this.SendPropertyChanging();
					this._PYM = value;
					this.SendPropertyChanged("PYM");
					this.OnPYMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XB", DbType="Char(4)")]
		public string XB
		{
			get
			{
				return this._XB;
			}
			set
			{
				if ((this._XB != value))
				{
					this.OnXBChanging(value);
					this.SendPropertyChanging();
					this._XB = value;
					this.SendPropertyChanged("XB");
					this.OnXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSRQ", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CSRQ
		{
			get
			{
				return this._CSRQ;
			}
			set
			{
				if ((this._CSRQ != value))
				{
					this.OnCSRQChanging(value);
					this.SendPropertyChanging();
					this._CSRQ = value;
					this.SendPropertyChanged("CSRQ");
					this.OnCSRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZCDM", DbType="SmallInt")]
		public System.Nullable<short> ZCDM
		{
			get
			{
				return this._ZCDM;
			}
			set
			{
				if ((this._ZCDM != value))
				{
					this.OnZCDMChanging(value);
					this.SendPropertyChanging();
					this._ZCDM = value;
					this.SendPropertyChanged("ZCDM");
					this.OnZCDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZYZH", DbType="VarChar(50)")]
		public string ZYZH
		{
			get
			{
				return this._ZYZH;
			}
			set
			{
				if ((this._ZYZH != value))
				{
					this.OnZYZHChanging(value);
					this.SendPropertyChanging();
					this._ZYZH = value;
					this.SendPropertyChanged("ZYZH");
					this.OnZYZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZGLBDM", DbType="TinyInt")]
		public System.Nullable<byte> ZGLBDM
		{
			get
			{
				return this._ZGLBDM;
			}
			set
			{
				if ((this._ZGLBDM != value))
				{
					this.OnZGLBDMChanging(value);
					this.SendPropertyChanging();
					this._ZGLBDM = value;
					this.SendPropertyChanged("ZGLBDM");
					this.OnZGLBDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HY", DbType="VarChar(20)")]
		public string HY
		{
			get
			{
				return this._HY;
			}
			set
			{
				if ((this._HY != value))
				{
					this.OnHYChanging(value);
					this.SendPropertyChanging();
					this._HY = value;
					this.SendPropertyChanged("HY");
					this.OnHYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZZMM", DbType="VarChar(20)")]
		public string ZZMM
		{
			get
			{
				return this._ZZMM;
			}
			set
			{
				if ((this._ZZMM != value))
				{
					this.OnZZMMChanging(value);
					this.SendPropertyChanging();
					this._ZZMM = value;
					this.SendPropertyChanged("ZZMM");
					this.OnZZMMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MM", DbType="VarChar(256)")]
		public string MM
		{
			get
			{
				return this._MM;
			}
			set
			{
				if ((this._MM != value))
				{
					this.OnMMChanging(value);
					this.SendPropertyChanging();
					this._MM = value;
					this.SendPropertyChanged("MM");
					this.OnMMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFZH", DbType="VarChar(20)")]
		public string SFZH
		{
			get
			{
				return this._SFZH;
			}
			set
			{
				if ((this._SFZH != value))
				{
					this.OnSFZHChanging(value);
					this.SendPropertyChanging();
					this._SFZH = value;
					this.SendPropertyChanged("SFZH");
					this.OnSFZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMDM", DbType="SmallInt")]
		public System.Nullable<short> BMDM
		{
			get
			{
				return this._BMDM;
			}
			set
			{
				if ((this._BMDM != value))
				{
					if (this._BM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBMDMChanging(value);
					this.SendPropertyChanging();
					this._BMDM = value;
					this.SendPropertyChanged("BMDM");
					this.OnBMDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRBH", DbType="VarChar(20)")]
		public string GRBH
		{
			get
			{
				return this._GRBH;
			}
			set
			{
				if ((this._GRBH != value))
				{
					this.OnGRBHChanging(value);
					this.SendPropertyChanging();
					this._GRBH = value;
					this.SendPropertyChanged("GRBH");
					this.OnGRBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXDH", DbType="VarChar(30)")]
		public string LXDH
		{
			get
			{
				return this._LXDH;
			}
			set
			{
				if ((this._LXDH != value))
				{
					this.OnLXDHChanging(value);
					this.SendPropertyChanging();
					this._LXDH = value;
					this.SendPropertyChanged("LXDH");
					this.OnLXDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XL", DbType="VarChar(20)")]
		public string XL
		{
			get
			{
				return this._XL;
			}
			set
			{
				if ((this._XL != value))
				{
					this.OnXLChanging(value);
					this.SendPropertyChanging();
					this._XL = value;
					this.SendPropertyChanged("XL");
					this.OnXLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JG", DbType="VarChar(100)")]
		public string JG
		{
			get
			{
				return this._JG;
			}
			set
			{
				if ((this._JG != value))
				{
					this.OnJGChanging(value);
					this.SendPropertyChanging();
					this._JG = value;
					this.SendPropertyChanged("JG");
					this.OnJGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFJY", DbType="Bit")]
		public System.Nullable<bool> SFJY
		{
			get
			{
				return this._SFJY;
			}
			set
			{
				if ((this._SFJY != value))
				{
					this.OnSFJYChanging(value);
					this.SendPropertyChanging();
					this._SFJY = value;
					this.SendPropertyChanged("SFJY");
					this.OnSFJYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary IMAGE
		{
			get
			{
				return this._IMAGE;
			}
			set
			{
				if ((this._IMAGE != value))
				{
					this.OnIMAGEChanging(value);
					this.SendPropertyChanging();
					this._IMAGE = value;
					this.SendPropertyChanged("IMAGE");
					this.OnIMAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(100)")]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this.OnBZChanging(value);
					this.SendPropertyChanging();
					this._BZ = value;
					this.SendPropertyChanged("BZ");
					this.OnBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DZ", DbType="VarChar(100)")]
		public string DZ
		{
			get
			{
				return this._DZ;
			}
			set
			{
				if ((this._DZ != value))
				{
					this.OnDZChanging(value);
					this.SendPropertyChanging();
					this._DZ = value;
					this.SendPropertyChanged("DZ");
					this.OnDZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WBM", DbType="VarChar(10)")]
		public string WBM
		{
			get
			{
				return this._WBM;
			}
			set
			{
				if ((this._WBM != value))
				{
					this.OnWBMChanging(value);
					this.SendPropertyChanging();
					this._WBM = value;
					this.SendPropertyChanged("WBM");
					this.OnWBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BM_ZG", Storage="_BM", ThisKey="BMDM", OtherKey="BMDM", IsForeignKey=true)]
		public BM BM
		{
			get
			{
				return this._BM.Entity;
			}
			set
			{
				BM previousValue = this._BM.Entity;
				if (((previousValue != value) 
							|| (this._BM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BM.Entity = null;
						previousValue.ZG.Remove(this);
					}
					this._BM.Entity = value;
					if ((value != null))
					{
						value.ZG.Add(this);
						this._BMDM = value.BMDM;
					}
					else
					{
						this._BMDM = default(Nullable<short>);
					}
					this.SendPropertyChanged("BM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZYBR")]
	public partial class ZYBR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ZYH;
		
		private short _MZDM;
		
		private System.Nullable<int> _BAH;
		
		private System.Nullable<int> _CKH;
		
		private string _YBKH;
		
		private string _BRXM;
		
		private string _XB;
		
		private System.Nullable<System.DateTime> _CSRQ;
		
		private string _HYZK;
		
		private string _CSD_SS;
		
		private string _CSD_XQ;
		
		private string _CSD_Z;
		
		private string _GJ;
		
		private string _SFZH;
		
		private string _ZY;
		
		private System.Nullable<short> _mzks;
		
		private System.Nullable<short> _NL;
		
		private string _JSDW;
		
		private EntitySet<RY> _RY;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZYHChanging(int value);
    partial void OnZYHChanged();
    partial void OnMZDMChanging(short value);
    partial void OnMZDMChanged();
    partial void OnBAHChanging(System.Nullable<int> value);
    partial void OnBAHChanged();
    partial void OnCKHChanging(System.Nullable<int> value);
    partial void OnCKHChanged();
    partial void OnYBKHChanging(string value);
    partial void OnYBKHChanged();
    partial void OnBRXMChanging(string value);
    partial void OnBRXMChanged();
    partial void OnXBChanging(string value);
    partial void OnXBChanged();
    partial void OnCSRQChanging(System.Nullable<System.DateTime> value);
    partial void OnCSRQChanged();
    partial void OnHYZKChanging(string value);
    partial void OnHYZKChanged();
    partial void OnCSD_SSChanging(string value);
    partial void OnCSD_SSChanged();
    partial void OnCSD_XQChanging(string value);
    partial void OnCSD_XQChanged();
    partial void OnCSD_ZChanging(string value);
    partial void OnCSD_ZChanged();
    partial void OnGJChanging(string value);
    partial void OnGJChanged();
    partial void OnSFZHChanging(string value);
    partial void OnSFZHChanged();
    partial void OnZYChanging(string value);
    partial void OnZYChanged();
    partial void OnmzksChanging(System.Nullable<short> value);
    partial void OnmzksChanged();
    partial void OnNLChanging(System.Nullable<short> value);
    partial void OnNLChanged();
    partial void OnJSDWChanging(string value);
    partial void OnJSDWChanged();
    #endregion
		
		public ZYBR()
		{
			this._RY = new EntitySet<RY>(new Action<RY>(this.attach_RY), new Action<RY>(this.detach_RY));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZYH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ZYH
		{
			get
			{
				return this._ZYH;
			}
			set
			{
				if ((this._ZYH != value))
				{
					this.OnZYHChanging(value);
					this.SendPropertyChanging();
					this._ZYH = value;
					this.SendPropertyChanged("ZYH");
					this.OnZYHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MZDM", DbType="SmallInt NOT NULL")]
		public short MZDM
		{
			get
			{
				return this._MZDM;
			}
			set
			{
				if ((this._MZDM != value))
				{
					this.OnMZDMChanging(value);
					this.SendPropertyChanging();
					this._MZDM = value;
					this.SendPropertyChanged("MZDM");
					this.OnMZDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAH", DbType="Int")]
		public System.Nullable<int> BAH
		{
			get
			{
				return this._BAH;
			}
			set
			{
				if ((this._BAH != value))
				{
					this.OnBAHChanging(value);
					this.SendPropertyChanging();
					this._BAH = value;
					this.SendPropertyChanged("BAH");
					this.OnBAHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CKH", DbType="Int")]
		public System.Nullable<int> CKH
		{
			get
			{
				return this._CKH;
			}
			set
			{
				if ((this._CKH != value))
				{
					this.OnCKHChanging(value);
					this.SendPropertyChanging();
					this._CKH = value;
					this.SendPropertyChanged("CKH");
					this.OnCKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YBKH", DbType="Char(20)")]
		public string YBKH
		{
			get
			{
				return this._YBKH;
			}
			set
			{
				if ((this._YBKH != value))
				{
					this.OnYBKHChanging(value);
					this.SendPropertyChanging();
					this._YBKH = value;
					this.SendPropertyChanged("YBKH");
					this.OnYBKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRXM", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string BRXM
		{
			get
			{
				return this._BRXM;
			}
			set
			{
				if ((this._BRXM != value))
				{
					this.OnBRXMChanging(value);
					this.SendPropertyChanging();
					this._BRXM = value;
					this.SendPropertyChanged("BRXM");
					this.OnBRXMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XB", DbType="Char(2)")]
		public string XB
		{
			get
			{
				return this._XB;
			}
			set
			{
				if ((this._XB != value))
				{
					this.OnXBChanging(value);
					this.SendPropertyChanging();
					this._XB = value;
					this.SendPropertyChanged("XB");
					this.OnXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> CSRQ
		{
			get
			{
				return this._CSRQ;
			}
			set
			{
				if ((this._CSRQ != value))
				{
					this.OnCSRQChanging(value);
					this.SendPropertyChanging();
					this._CSRQ = value;
					this.SendPropertyChanged("CSRQ");
					this.OnCSRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HYZK", DbType="Char(10)")]
		public string HYZK
		{
			get
			{
				return this._HYZK;
			}
			set
			{
				if ((this._HYZK != value))
				{
					this.OnHYZKChanging(value);
					this.SendPropertyChanging();
					this._HYZK = value;
					this.SendPropertyChanged("HYZK");
					this.OnHYZKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSD_SS", DbType="VarChar(30)")]
		public string CSD_SS
		{
			get
			{
				return this._CSD_SS;
			}
			set
			{
				if ((this._CSD_SS != value))
				{
					this.OnCSD_SSChanging(value);
					this.SendPropertyChanging();
					this._CSD_SS = value;
					this.SendPropertyChanged("CSD_SS");
					this.OnCSD_SSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSD_XQ", DbType="VarChar(30)")]
		public string CSD_XQ
		{
			get
			{
				return this._CSD_XQ;
			}
			set
			{
				if ((this._CSD_XQ != value))
				{
					this.OnCSD_XQChanging(value);
					this.SendPropertyChanging();
					this._CSD_XQ = value;
					this.SendPropertyChanged("CSD_XQ");
					this.OnCSD_XQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSD_Z", DbType="VarChar(30)")]
		public string CSD_Z
		{
			get
			{
				return this._CSD_Z;
			}
			set
			{
				if ((this._CSD_Z != value))
				{
					this.OnCSD_ZChanging(value);
					this.SendPropertyChanging();
					this._CSD_Z = value;
					this.SendPropertyChanged("CSD_Z");
					this.OnCSD_ZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GJ", DbType="VarChar(10)")]
		public string GJ
		{
			get
			{
				return this._GJ;
			}
			set
			{
				if ((this._GJ != value))
				{
					this.OnGJChanging(value);
					this.SendPropertyChanging();
					this._GJ = value;
					this.SendPropertyChanged("GJ");
					this.OnGJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFZH", DbType="VarChar(20)")]
		public string SFZH
		{
			get
			{
				return this._SFZH;
			}
			set
			{
				if ((this._SFZH != value))
				{
					this.OnSFZHChanging(value);
					this.SendPropertyChanging();
					this._SFZH = value;
					this.SendPropertyChanged("SFZH");
					this.OnSFZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZY", DbType="VarChar(20)")]
		public string ZY
		{
			get
			{
				return this._ZY;
			}
			set
			{
				if ((this._ZY != value))
				{
					this.OnZYChanging(value);
					this.SendPropertyChanging();
					this._ZY = value;
					this.SendPropertyChanged("ZY");
					this.OnZYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzks", DbType="SmallInt")]
		public System.Nullable<short> mzks
		{
			get
			{
				return this._mzks;
			}
			set
			{
				if ((this._mzks != value))
				{
					this.OnmzksChanging(value);
					this.SendPropertyChanging();
					this._mzks = value;
					this.SendPropertyChanged("mzks");
					this.OnmzksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NL", DbType="SmallInt")]
		public System.Nullable<short> NL
		{
			get
			{
				return this._NL;
			}
			set
			{
				if ((this._NL != value))
				{
					this.OnNLChanging(value);
					this.SendPropertyChanging();
					this._NL = value;
					this.SendPropertyChanged("NL");
					this.OnNLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JSDW", DbType="Char(10)")]
		public string JSDW
		{
			get
			{
				return this._JSDW;
			}
			set
			{
				if ((this._JSDW != value))
				{
					this.OnJSDWChanging(value);
					this.SendPropertyChanging();
					this._JSDW = value;
					this.SendPropertyChanged("JSDW");
					this.OnJSDWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ZYBR_RY", Storage="_RY", ThisKey="ZYH", OtherKey="ZYH")]
		public EntitySet<RY> RY
		{
			get
			{
				return this._RY;
			}
			set
			{
				this._RY.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RY(RY entity)
		{
			this.SendPropertyChanging();
			entity.ZYBR = this;
		}
		
		private void detach_RY(RY entity)
		{
			this.SendPropertyChanging();
			entity.ZYBR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RY")]
	public partial class RY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RYH;
		
		private int _ZYH;
		
		private short _RYKS;
		
		private byte _ZYBRLX;
		
		private decimal _RYYJJE;
		
		private System.Nullable<decimal> _BJX;
		
		private decimal _YJKZJE;
		
		private decimal _JZZJE;
		
		private System.DateTime _RYRQ;
		
		private System.Nullable<System.DateTime> _CYRQ;
		
		private byte _RYQKDM;
		
		private decimal _QFZJE;
		
		private decimal _XJJFZJE;
		
		private decimal _CWFZJE;
		
		private decimal _CYBJJE;
		
		private decimal _YE;
		
		private decimal _BXJE;
		
		private System.Nullable<short> _YS;
		
		private short _CZY;
		
		private byte _ZT;
		
		private byte _ZF;
		
		private short _RYCH;
		
		private string _YBBM;
		
		private System.Nullable<short> _YLFKFSDM;
		
		private System.Nullable<short> _KSDM;
		
		private System.Nullable<byte> _ycy;
		
		private System.Nullable<System.DateTime> _REGCARD_DATE;
		
		private System.Nullable<System.DateTime> _YCYRQ;
		
		private string _HZ_HZZH;
		
		private string _RegID;
		
		private System.Nullable<decimal> _JZZJE_YS;
		
		private string _HZ_REG;
		
		private System.Nullable<int> _PatientID;
		
		private System.Nullable<System.DateTime> _JBSJ;
		
		private string _FLAG;
		
		private System.Nullable<short> _BudgetDay;
		
		private EntityRef<BASY> _BASY;
		
		private EntityRef<BM> _BM;
		
		private EntityRef<ZYBR> _ZYBR;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRYHChanging(int value);
    partial void OnRYHChanged();
    partial void OnZYHChanging(int value);
    partial void OnZYHChanged();
    partial void OnRYKSChanging(short value);
    partial void OnRYKSChanged();
    partial void OnZYBRLXChanging(byte value);
    partial void OnZYBRLXChanged();
    partial void OnRYYJJEChanging(decimal value);
    partial void OnRYYJJEChanged();
    partial void OnBJXChanging(System.Nullable<decimal> value);
    partial void OnBJXChanged();
    partial void OnYJKZJEChanging(decimal value);
    partial void OnYJKZJEChanged();
    partial void OnJZZJEChanging(decimal value);
    partial void OnJZZJEChanged();
    partial void OnRYRQChanging(System.DateTime value);
    partial void OnRYRQChanged();
    partial void OnCYRQChanging(System.Nullable<System.DateTime> value);
    partial void OnCYRQChanged();
    partial void OnRYQKDMChanging(byte value);
    partial void OnRYQKDMChanged();
    partial void OnQFZJEChanging(decimal value);
    partial void OnQFZJEChanged();
    partial void OnXJJFZJEChanging(decimal value);
    partial void OnXJJFZJEChanged();
    partial void OnCWFZJEChanging(decimal value);
    partial void OnCWFZJEChanged();
    partial void OnCYBJJEChanging(decimal value);
    partial void OnCYBJJEChanged();
    partial void OnYEChanging(decimal value);
    partial void OnYEChanged();
    partial void OnBXJEChanging(decimal value);
    partial void OnBXJEChanged();
    partial void OnYSChanging(System.Nullable<short> value);
    partial void OnYSChanged();
    partial void OnCZYChanging(short value);
    partial void OnCZYChanged();
    partial void OnZTChanging(byte value);
    partial void OnZTChanged();
    partial void OnZFChanging(byte value);
    partial void OnZFChanged();
    partial void OnRYCHChanging(short value);
    partial void OnRYCHChanged();
    partial void OnYBBMChanging(string value);
    partial void OnYBBMChanged();
    partial void OnYLFKFSDMChanging(System.Nullable<short> value);
    partial void OnYLFKFSDMChanged();
    partial void OnKSDMChanging(System.Nullable<short> value);
    partial void OnKSDMChanged();
    partial void OnycyChanging(System.Nullable<byte> value);
    partial void OnycyChanged();
    partial void OnREGCARD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnREGCARD_DATEChanged();
    partial void OnYCYRQChanging(System.Nullable<System.DateTime> value);
    partial void OnYCYRQChanged();
    partial void OnHZ_HZZHChanging(string value);
    partial void OnHZ_HZZHChanged();
    partial void OnRegIDChanging(string value);
    partial void OnRegIDChanged();
    partial void OnJZZJE_YSChanging(System.Nullable<decimal> value);
    partial void OnJZZJE_YSChanged();
    partial void OnHZ_REGChanging(string value);
    partial void OnHZ_REGChanged();
    partial void OnPatientIDChanging(System.Nullable<int> value);
    partial void OnPatientIDChanged();
    partial void OnJBSJChanging(System.Nullable<System.DateTime> value);
    partial void OnJBSJChanged();
    partial void OnFLAGChanging(string value);
    partial void OnFLAGChanged();
    partial void OnBudgetDayChanging(System.Nullable<short> value);
    partial void OnBudgetDayChanged();
    #endregion
		
		public RY()
		{
			this._BASY = default(EntityRef<BASY>);
			this._BM = default(EntityRef<BM>);
			this._ZYBR = default(EntityRef<ZYBR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RYH
		{
			get
			{
				return this._RYH;
			}
			set
			{
				if ((this._RYH != value))
				{
					this.OnRYHChanging(value);
					this.SendPropertyChanging();
					this._RYH = value;
					this.SendPropertyChanged("RYH");
					this.OnRYHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZYH", DbType="Int NOT NULL")]
		public int ZYH
		{
			get
			{
				return this._ZYH;
			}
			set
			{
				if ((this._ZYH != value))
				{
					if (this._ZYBR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnZYHChanging(value);
					this.SendPropertyChanging();
					this._ZYH = value;
					this.SendPropertyChanged("ZYH");
					this.OnZYHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYKS", DbType="SmallInt NOT NULL")]
		public short RYKS
		{
			get
			{
				return this._RYKS;
			}
			set
			{
				if ((this._RYKS != value))
				{
					if (this._BM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRYKSChanging(value);
					this.SendPropertyChanging();
					this._RYKS = value;
					this.SendPropertyChanged("RYKS");
					this.OnRYKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZYBRLX", DbType="TinyInt NOT NULL")]
		public byte ZYBRLX
		{
			get
			{
				return this._ZYBRLX;
			}
			set
			{
				if ((this._ZYBRLX != value))
				{
					this.OnZYBRLXChanging(value);
					this.SendPropertyChanging();
					this._ZYBRLX = value;
					this.SendPropertyChanged("ZYBRLX");
					this.OnZYBRLXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYYJJE", DbType="Money NOT NULL")]
		public decimal RYYJJE
		{
			get
			{
				return this._RYYJJE;
			}
			set
			{
				if ((this._RYYJJE != value))
				{
					this.OnRYYJJEChanging(value);
					this.SendPropertyChanging();
					this._RYYJJE = value;
					this.SendPropertyChanged("RYYJJE");
					this.OnRYYJJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJX", DbType="Money")]
		public System.Nullable<decimal> BJX
		{
			get
			{
				return this._BJX;
			}
			set
			{
				if ((this._BJX != value))
				{
					this.OnBJXChanging(value);
					this.SendPropertyChanging();
					this._BJX = value;
					this.SendPropertyChanged("BJX");
					this.OnBJXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YJKZJE", DbType="Money NOT NULL")]
		public decimal YJKZJE
		{
			get
			{
				return this._YJKZJE;
			}
			set
			{
				if ((this._YJKZJE != value))
				{
					this.OnYJKZJEChanging(value);
					this.SendPropertyChanging();
					this._YJKZJE = value;
					this.SendPropertyChanged("YJKZJE");
					this.OnYJKZJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JZZJE", DbType="Money NOT NULL")]
		public decimal JZZJE
		{
			get
			{
				return this._JZZJE;
			}
			set
			{
				if ((this._JZZJE != value))
				{
					this.OnJZZJEChanging(value);
					this.SendPropertyChanging();
					this._JZZJE = value;
					this.SendPropertyChanged("JZZJE");
					this.OnJZZJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYRQ", DbType="DateTime NOT NULL")]
		public System.DateTime RYRQ
		{
			get
			{
				return this._RYRQ;
			}
			set
			{
				if ((this._RYRQ != value))
				{
					this.OnRYRQChanging(value);
					this.SendPropertyChanging();
					this._RYRQ = value;
					this.SendPropertyChanged("RYRQ");
					this.OnRYRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CYRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> CYRQ
		{
			get
			{
				return this._CYRQ;
			}
			set
			{
				if ((this._CYRQ != value))
				{
					this.OnCYRQChanging(value);
					this.SendPropertyChanging();
					this._CYRQ = value;
					this.SendPropertyChanged("CYRQ");
					this.OnCYRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYQKDM", DbType="TinyInt NOT NULL")]
		public byte RYQKDM
		{
			get
			{
				return this._RYQKDM;
			}
			set
			{
				if ((this._RYQKDM != value))
				{
					this.OnRYQKDMChanging(value);
					this.SendPropertyChanging();
					this._RYQKDM = value;
					this.SendPropertyChanged("RYQKDM");
					this.OnRYQKDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QFZJE", DbType="Money NOT NULL")]
		public decimal QFZJE
		{
			get
			{
				return this._QFZJE;
			}
			set
			{
				if ((this._QFZJE != value))
				{
					this.OnQFZJEChanging(value);
					this.SendPropertyChanging();
					this._QFZJE = value;
					this.SendPropertyChanged("QFZJE");
					this.OnQFZJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XJJFZJE", DbType="Money NOT NULL")]
		public decimal XJJFZJE
		{
			get
			{
				return this._XJJFZJE;
			}
			set
			{
				if ((this._XJJFZJE != value))
				{
					this.OnXJJFZJEChanging(value);
					this.SendPropertyChanging();
					this._XJJFZJE = value;
					this.SendPropertyChanged("XJJFZJE");
					this.OnXJJFZJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CWFZJE", DbType="Money NOT NULL")]
		public decimal CWFZJE
		{
			get
			{
				return this._CWFZJE;
			}
			set
			{
				if ((this._CWFZJE != value))
				{
					this.OnCWFZJEChanging(value);
					this.SendPropertyChanging();
					this._CWFZJE = value;
					this.SendPropertyChanged("CWFZJE");
					this.OnCWFZJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CYBJJE", DbType="Money NOT NULL")]
		public decimal CYBJJE
		{
			get
			{
				return this._CYBJJE;
			}
			set
			{
				if ((this._CYBJJE != value))
				{
					this.OnCYBJJEChanging(value);
					this.SendPropertyChanging();
					this._CYBJJE = value;
					this.SendPropertyChanged("CYBJJE");
					this.OnCYBJJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YE", DbType="Money NOT NULL")]
		public decimal YE
		{
			get
			{
				return this._YE;
			}
			set
			{
				if ((this._YE != value))
				{
					this.OnYEChanging(value);
					this.SendPropertyChanging();
					this._YE = value;
					this.SendPropertyChanged("YE");
					this.OnYEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BXJE", DbType="Money NOT NULL")]
		public decimal BXJE
		{
			get
			{
				return this._BXJE;
			}
			set
			{
				if ((this._BXJE != value))
				{
					this.OnBXJEChanging(value);
					this.SendPropertyChanging();
					this._BXJE = value;
					this.SendPropertyChanged("BXJE");
					this.OnBXJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YS", DbType="SmallInt")]
		public System.Nullable<short> YS
		{
			get
			{
				return this._YS;
			}
			set
			{
				if ((this._YS != value))
				{
					this.OnYSChanging(value);
					this.SendPropertyChanging();
					this._YS = value;
					this.SendPropertyChanged("YS");
					this.OnYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CZY", DbType="SmallInt NOT NULL")]
		public short CZY
		{
			get
			{
				return this._CZY;
			}
			set
			{
				if ((this._CZY != value))
				{
					this.OnCZYChanging(value);
					this.SendPropertyChanging();
					this._CZY = value;
					this.SendPropertyChanged("CZY");
					this.OnCZYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZT", DbType="TinyInt NOT NULL")]
		public byte ZT
		{
			get
			{
				return this._ZT;
			}
			set
			{
				if ((this._ZT != value))
				{
					this.OnZTChanging(value);
					this.SendPropertyChanging();
					this._ZT = value;
					this.SendPropertyChanged("ZT");
					this.OnZTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZF", DbType="TinyInt NOT NULL")]
		public byte ZF
		{
			get
			{
				return this._ZF;
			}
			set
			{
				if ((this._ZF != value))
				{
					this.OnZFChanging(value);
					this.SendPropertyChanging();
					this._ZF = value;
					this.SendPropertyChanged("ZF");
					this.OnZFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYCH", DbType="SmallInt NOT NULL")]
		public short RYCH
		{
			get
			{
				return this._RYCH;
			}
			set
			{
				if ((this._RYCH != value))
				{
					this.OnRYCHChanging(value);
					this.SendPropertyChanging();
					this._RYCH = value;
					this.SendPropertyChanged("RYCH");
					this.OnRYCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YBBM", DbType="Char(20)")]
		public string YBBM
		{
			get
			{
				return this._YBBM;
			}
			set
			{
				if ((this._YBBM != value))
				{
					this.OnYBBMChanging(value);
					this.SendPropertyChanging();
					this._YBBM = value;
					this.SendPropertyChanged("YBBM");
					this.OnYBBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YLFKFSDM", DbType="SmallInt")]
		public System.Nullable<short> YLFKFSDM
		{
			get
			{
				return this._YLFKFSDM;
			}
			set
			{
				if ((this._YLFKFSDM != value))
				{
					this.OnYLFKFSDMChanging(value);
					this.SendPropertyChanging();
					this._YLFKFSDM = value;
					this.SendPropertyChanged("YLFKFSDM");
					this.OnYLFKFSDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KSDM", DbType="SmallInt")]
		public System.Nullable<short> KSDM
		{
			get
			{
				return this._KSDM;
			}
			set
			{
				if ((this._KSDM != value))
				{
					this.OnKSDMChanging(value);
					this.SendPropertyChanging();
					this._KSDM = value;
					this.SendPropertyChanged("KSDM");
					this.OnKSDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ycy", DbType="TinyInt")]
		public System.Nullable<byte> ycy
		{
			get
			{
				return this._ycy;
			}
			set
			{
				if ((this._ycy != value))
				{
					this.OnycyChanging(value);
					this.SendPropertyChanging();
					this._ycy = value;
					this.SendPropertyChanged("ycy");
					this.OnycyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGCARD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> REGCARD_DATE
		{
			get
			{
				return this._REGCARD_DATE;
			}
			set
			{
				if ((this._REGCARD_DATE != value))
				{
					this.OnREGCARD_DATEChanging(value);
					this.SendPropertyChanging();
					this._REGCARD_DATE = value;
					this.SendPropertyChanged("REGCARD_DATE");
					this.OnREGCARD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YCYRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> YCYRQ
		{
			get
			{
				return this._YCYRQ;
			}
			set
			{
				if ((this._YCYRQ != value))
				{
					this.OnYCYRQChanging(value);
					this.SendPropertyChanging();
					this._YCYRQ = value;
					this.SendPropertyChanged("YCYRQ");
					this.OnYCYRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HZ_HZZH", DbType="VarChar(40)")]
		public string HZ_HZZH
		{
			get
			{
				return this._HZ_HZZH;
			}
			set
			{
				if ((this._HZ_HZZH != value))
				{
					this.OnHZ_HZZHChanging(value);
					this.SendPropertyChanging();
					this._HZ_HZZH = value;
					this.SendPropertyChanged("HZ_HZZH");
					this.OnHZ_HZZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", DbType="VarChar(20)")]
		public string RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					this.OnRegIDChanging(value);
					this.SendPropertyChanging();
					this._RegID = value;
					this.SendPropertyChanged("RegID");
					this.OnRegIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JZZJE_YS", DbType="Money")]
		public System.Nullable<decimal> JZZJE_YS
		{
			get
			{
				return this._JZZJE_YS;
			}
			set
			{
				if ((this._JZZJE_YS != value))
				{
					this.OnJZZJE_YSChanging(value);
					this.SendPropertyChanging();
					this._JZZJE_YS = value;
					this.SendPropertyChanged("JZZJE_YS");
					this.OnJZZJE_YSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HZ_REG", DbType="VarChar(40)")]
		public string HZ_REG
		{
			get
			{
				return this._HZ_REG;
			}
			set
			{
				if ((this._HZ_REG != value))
				{
					this.OnHZ_REGChanging(value);
					this.SendPropertyChanging();
					this._HZ_REG = value;
					this.SendPropertyChanged("HZ_REG");
					this.OnHZ_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int")]
		public System.Nullable<int> PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this.OnPatientIDChanging(value);
					this.SendPropertyChanging();
					this._PatientID = value;
					this.SendPropertyChanged("PatientID");
					this.OnPatientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JBSJ", DbType="DateTime")]
		public System.Nullable<System.DateTime> JBSJ
		{
			get
			{
				return this._JBSJ;
			}
			set
			{
				if ((this._JBSJ != value))
				{
					this.OnJBSJChanging(value);
					this.SendPropertyChanging();
					this._JBSJ = value;
					this.SendPropertyChanged("JBSJ");
					this.OnJBSJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(10)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetDay", DbType="SmallInt")]
		public System.Nullable<short> BudgetDay
		{
			get
			{
				return this._BudgetDay;
			}
			set
			{
				if ((this._BudgetDay != value))
				{
					this.OnBudgetDayChanging(value);
					this.SendPropertyChanging();
					this._BudgetDay = value;
					this.SendPropertyChanged("BudgetDay");
					this.OnBudgetDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RY_BASY", Storage="_BASY", ThisKey="RYH", OtherKey="RYH", IsUnique=true, IsForeignKey=false)]
		public BASY BASY
		{
			get
			{
				return this._BASY.Entity;
			}
			set
			{
				BASY previousValue = this._BASY.Entity;
				if (((previousValue != value) 
							|| (this._BASY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BASY.Entity = null;
						previousValue.RY = null;
					}
					this._BASY.Entity = value;
					if ((value != null))
					{
						value.RY = this;
					}
					this.SendPropertyChanged("BASY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BM_RY", Storage="_BM", ThisKey="RYKS", OtherKey="BMDM", IsForeignKey=true)]
		public BM BM
		{
			get
			{
				return this._BM.Entity;
			}
			set
			{
				BM previousValue = this._BM.Entity;
				if (((previousValue != value) 
							|| (this._BM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BM.Entity = null;
						previousValue.RY.Remove(this);
					}
					this._BM.Entity = value;
					if ((value != null))
					{
						value.RY.Add(this);
						this._RYKS = value.BMDM;
					}
					else
					{
						this._RYKS = default(short);
					}
					this.SendPropertyChanged("BM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ZYBR_RY", Storage="_ZYBR", ThisKey="ZYH", OtherKey="ZYH", IsForeignKey=true)]
		public ZYBR ZYBR
		{
			get
			{
				return this._ZYBR.Entity;
			}
			set
			{
				ZYBR previousValue = this._ZYBR.Entity;
				if (((previousValue != value) 
							|| (this._ZYBR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ZYBR.Entity = null;
						previousValue.RY.Remove(this);
					}
					this._ZYBR.Entity = value;
					if ((value != null))
					{
						value.RY.Add(this);
						this._ZYH = value.ZYH;
					}
					else
					{
						this._ZYH = default(int);
					}
					this.SendPropertyChanged("ZYBR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BASY")]
	public partial class BASY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RYH;
		
		private string _GZDW_DZ;
		
		private string _GZDW_DH;
		
		private string _GZDW_YZBM;
		
		private string _HK_DZ;
		
		private string _HK_YZBM;
		
		private string _LXR_XM;
		
		private string _LXR_GX;
		
		private string _LXR_DZ;
		
		private string _LXR_DH;
		
		private string _MZZD_ICD;
		
		private string _MZZD;
		
		private string _RYZD_ICD;
		
		private string _RYZD;
		
		private string _CYZYZD_ICD;
		
		private string _CYZYZD;
		
		private string _CYZYZD_LX;
		
		private System.Nullable<short> _MZZD_YS;
		
		private System.Nullable<short> _nl;
		
		private string _jsdw;
		
		private string _DBR;
		
		private string _bscsz;
		
		private string _kkcd;
		
		private string _cyzyzd_zdyj;
		
		private EntityRef<RY> _RY;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRYHChanging(int value);
    partial void OnRYHChanged();
    partial void OnGZDW_DZChanging(string value);
    partial void OnGZDW_DZChanged();
    partial void OnGZDW_DHChanging(string value);
    partial void OnGZDW_DHChanged();
    partial void OnGZDW_YZBMChanging(string value);
    partial void OnGZDW_YZBMChanged();
    partial void OnHK_DZChanging(string value);
    partial void OnHK_DZChanged();
    partial void OnHK_YZBMChanging(string value);
    partial void OnHK_YZBMChanged();
    partial void OnLXR_XMChanging(string value);
    partial void OnLXR_XMChanged();
    partial void OnLXR_GXChanging(string value);
    partial void OnLXR_GXChanged();
    partial void OnLXR_DZChanging(string value);
    partial void OnLXR_DZChanged();
    partial void OnLXR_DHChanging(string value);
    partial void OnLXR_DHChanged();
    partial void OnMZZD_ICDChanging(string value);
    partial void OnMZZD_ICDChanged();
    partial void OnMZZDChanging(string value);
    partial void OnMZZDChanged();
    partial void OnRYZD_ICDChanging(string value);
    partial void OnRYZD_ICDChanged();
    partial void OnRYZDChanging(string value);
    partial void OnRYZDChanged();
    partial void OnCYZYZD_ICDChanging(string value);
    partial void OnCYZYZD_ICDChanged();
    partial void OnCYZYZDChanging(string value);
    partial void OnCYZYZDChanged();
    partial void OnCYZYZD_LXChanging(string value);
    partial void OnCYZYZD_LXChanged();
    partial void OnMZZD_YSChanging(System.Nullable<short> value);
    partial void OnMZZD_YSChanged();
    partial void OnnlChanging(System.Nullable<short> value);
    partial void OnnlChanged();
    partial void OnjsdwChanging(string value);
    partial void OnjsdwChanged();
    partial void OnDBRChanging(string value);
    partial void OnDBRChanged();
    partial void OnbscszChanging(string value);
    partial void OnbscszChanged();
    partial void OnkkcdChanging(string value);
    partial void OnkkcdChanged();
    partial void Oncyzyzd_zdyjChanging(string value);
    partial void Oncyzyzd_zdyjChanged();
    #endregion
		
		public BASY()
		{
			this._RY = default(EntityRef<RY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RYH
		{
			get
			{
				return this._RYH;
			}
			set
			{
				if ((this._RYH != value))
				{
					if (this._RY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRYHChanging(value);
					this.SendPropertyChanging();
					this._RYH = value;
					this.SendPropertyChanged("RYH");
					this.OnRYHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GZDW_DZ", DbType="VarChar(60)")]
		public string GZDW_DZ
		{
			get
			{
				return this._GZDW_DZ;
			}
			set
			{
				if ((this._GZDW_DZ != value))
				{
					this.OnGZDW_DZChanging(value);
					this.SendPropertyChanging();
					this._GZDW_DZ = value;
					this.SendPropertyChanged("GZDW_DZ");
					this.OnGZDW_DZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GZDW_DH", DbType="VarChar(40)")]
		public string GZDW_DH
		{
			get
			{
				return this._GZDW_DH;
			}
			set
			{
				if ((this._GZDW_DH != value))
				{
					this.OnGZDW_DHChanging(value);
					this.SendPropertyChanging();
					this._GZDW_DH = value;
					this.SendPropertyChanged("GZDW_DH");
					this.OnGZDW_DHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GZDW_YZBM", DbType="VarChar(10)")]
		public string GZDW_YZBM
		{
			get
			{
				return this._GZDW_YZBM;
			}
			set
			{
				if ((this._GZDW_YZBM != value))
				{
					this.OnGZDW_YZBMChanging(value);
					this.SendPropertyChanging();
					this._GZDW_YZBM = value;
					this.SendPropertyChanged("GZDW_YZBM");
					this.OnGZDW_YZBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HK_DZ", DbType="VarChar(60)")]
		public string HK_DZ
		{
			get
			{
				return this._HK_DZ;
			}
			set
			{
				if ((this._HK_DZ != value))
				{
					this.OnHK_DZChanging(value);
					this.SendPropertyChanging();
					this._HK_DZ = value;
					this.SendPropertyChanged("HK_DZ");
					this.OnHK_DZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HK_YZBM", DbType="VarChar(10)")]
		public string HK_YZBM
		{
			get
			{
				return this._HK_YZBM;
			}
			set
			{
				if ((this._HK_YZBM != value))
				{
					this.OnHK_YZBMChanging(value);
					this.SendPropertyChanging();
					this._HK_YZBM = value;
					this.SendPropertyChanged("HK_YZBM");
					this.OnHK_YZBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXR_XM", DbType="VarChar(20)")]
		public string LXR_XM
		{
			get
			{
				return this._LXR_XM;
			}
			set
			{
				if ((this._LXR_XM != value))
				{
					this.OnLXR_XMChanging(value);
					this.SendPropertyChanging();
					this._LXR_XM = value;
					this.SendPropertyChanged("LXR_XM");
					this.OnLXR_XMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXR_GX", DbType="VarChar(20)")]
		public string LXR_GX
		{
			get
			{
				return this._LXR_GX;
			}
			set
			{
				if ((this._LXR_GX != value))
				{
					this.OnLXR_GXChanging(value);
					this.SendPropertyChanging();
					this._LXR_GX = value;
					this.SendPropertyChanged("LXR_GX");
					this.OnLXR_GXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXR_DZ", DbType="VarChar(80)")]
		public string LXR_DZ
		{
			get
			{
				return this._LXR_DZ;
			}
			set
			{
				if ((this._LXR_DZ != value))
				{
					this.OnLXR_DZChanging(value);
					this.SendPropertyChanging();
					this._LXR_DZ = value;
					this.SendPropertyChanged("LXR_DZ");
					this.OnLXR_DZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXR_DH", DbType="VarChar(40)")]
		public string LXR_DH
		{
			get
			{
				return this._LXR_DH;
			}
			set
			{
				if ((this._LXR_DH != value))
				{
					this.OnLXR_DHChanging(value);
					this.SendPropertyChanging();
					this._LXR_DH = value;
					this.SendPropertyChanged("LXR_DH");
					this.OnLXR_DHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MZZD_ICD", DbType="Char(20)")]
		public string MZZD_ICD
		{
			get
			{
				return this._MZZD_ICD;
			}
			set
			{
				if ((this._MZZD_ICD != value))
				{
					this.OnMZZD_ICDChanging(value);
					this.SendPropertyChanging();
					this._MZZD_ICD = value;
					this.SendPropertyChanged("MZZD_ICD");
					this.OnMZZD_ICDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MZZD", DbType="VarChar(100)")]
		public string MZZD
		{
			get
			{
				return this._MZZD;
			}
			set
			{
				if ((this._MZZD != value))
				{
					this.OnMZZDChanging(value);
					this.SendPropertyChanging();
					this._MZZD = value;
					this.SendPropertyChanged("MZZD");
					this.OnMZZDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYZD_ICD", DbType="Char(20)")]
		public string RYZD_ICD
		{
			get
			{
				return this._RYZD_ICD;
			}
			set
			{
				if ((this._RYZD_ICD != value))
				{
					this.OnRYZD_ICDChanging(value);
					this.SendPropertyChanging();
					this._RYZD_ICD = value;
					this.SendPropertyChanged("RYZD_ICD");
					this.OnRYZD_ICDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYZD", DbType="VarChar(100)")]
		public string RYZD
		{
			get
			{
				return this._RYZD;
			}
			set
			{
				if ((this._RYZD != value))
				{
					this.OnRYZDChanging(value);
					this.SendPropertyChanging();
					this._RYZD = value;
					this.SendPropertyChanged("RYZD");
					this.OnRYZDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CYZYZD_ICD", DbType="Char(20)")]
		public string CYZYZD_ICD
		{
			get
			{
				return this._CYZYZD_ICD;
			}
			set
			{
				if ((this._CYZYZD_ICD != value))
				{
					this.OnCYZYZD_ICDChanging(value);
					this.SendPropertyChanging();
					this._CYZYZD_ICD = value;
					this.SendPropertyChanged("CYZYZD_ICD");
					this.OnCYZYZD_ICDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CYZYZD", DbType="VarChar(100)")]
		public string CYZYZD
		{
			get
			{
				return this._CYZYZD;
			}
			set
			{
				if ((this._CYZYZD != value))
				{
					this.OnCYZYZDChanging(value);
					this.SendPropertyChanging();
					this._CYZYZD = value;
					this.SendPropertyChanged("CYZYZD");
					this.OnCYZYZDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CYZYZD_LX", DbType="Char(10)")]
		public string CYZYZD_LX
		{
			get
			{
				return this._CYZYZD_LX;
			}
			set
			{
				if ((this._CYZYZD_LX != value))
				{
					this.OnCYZYZD_LXChanging(value);
					this.SendPropertyChanging();
					this._CYZYZD_LX = value;
					this.SendPropertyChanged("CYZYZD_LX");
					this.OnCYZYZD_LXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MZZD_YS", DbType="SmallInt")]
		public System.Nullable<short> MZZD_YS
		{
			get
			{
				return this._MZZD_YS;
			}
			set
			{
				if ((this._MZZD_YS != value))
				{
					this.OnMZZD_YSChanging(value);
					this.SendPropertyChanging();
					this._MZZD_YS = value;
					this.SendPropertyChanged("MZZD_YS");
					this.OnMZZD_YSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nl", DbType="SmallInt")]
		public System.Nullable<short> nl
		{
			get
			{
				return this._nl;
			}
			set
			{
				if ((this._nl != value))
				{
					this.OnnlChanging(value);
					this.SendPropertyChanging();
					this._nl = value;
					this.SendPropertyChanged("nl");
					this.OnnlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jsdw", DbType="VarChar(10)")]
		public string jsdw
		{
			get
			{
				return this._jsdw;
			}
			set
			{
				if ((this._jsdw != value))
				{
					this.OnjsdwChanging(value);
					this.SendPropertyChanging();
					this._jsdw = value;
					this.SendPropertyChanged("jsdw");
					this.OnjsdwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBR", DbType="VarChar(30)")]
		public string DBR
		{
			get
			{
				return this._DBR;
			}
			set
			{
				if ((this._DBR != value))
				{
					this.OnDBRChanging(value);
					this.SendPropertyChanging();
					this._DBR = value;
					this.SendPropertyChanged("DBR");
					this.OnDBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bscsz", DbType="VarChar(20)")]
		public string bscsz
		{
			get
			{
				return this._bscsz;
			}
			set
			{
				if ((this._bscsz != value))
				{
					this.OnbscszChanging(value);
					this.SendPropertyChanging();
					this._bscsz = value;
					this.SendPropertyChanged("bscsz");
					this.OnbscszChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kkcd", DbType="VarChar(20)")]
		public string kkcd
		{
			get
			{
				return this._kkcd;
			}
			set
			{
				if ((this._kkcd != value))
				{
					this.OnkkcdChanging(value);
					this.SendPropertyChanging();
					this._kkcd = value;
					this.SendPropertyChanged("kkcd");
					this.OnkkcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cyzyzd_zdyj", DbType="VarChar(30)")]
		public string cyzyzd_zdyj
		{
			get
			{
				return this._cyzyzd_zdyj;
			}
			set
			{
				if ((this._cyzyzd_zdyj != value))
				{
					this.Oncyzyzd_zdyjChanging(value);
					this.SendPropertyChanging();
					this._cyzyzd_zdyj = value;
					this.SendPropertyChanged("cyzyzd_zdyj");
					this.Oncyzyzd_zdyjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RY_BASY", Storage="_RY", ThisKey="RYH", OtherKey="RYH", IsForeignKey=true)]
		public RY RY
		{
			get
			{
				return this._RY.Entity;
			}
			set
			{
				RY previousValue = this._RY.Entity;
				if (((previousValue != value) 
							|| (this._RY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RY.Entity = null;
						previousValue.BASY = null;
					}
					this._RY.Entity = value;
					if ((value != null))
					{
						value.BASY = this;
						this._RYH = value.RYH;
					}
					else
					{
						this._RYH = default(int);
					}
					this.SendPropertyChanged("RY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
