<?xml version="1.0" encoding="utf-8"?><Database Name="cbhis" Class="DCCbhisDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=cbhis;Integrated Security=True" SettingsObjectName="NCMS_Local.Properties.Settings" SettingsPropertyName="cbhisConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BM" Member="BM">
    <Type Name="BM">
      <Column Name="BMDM" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BMMC" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BMLBDM" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PYM" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="YJBMDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="KSLBDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KS_YBBM" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SFCW" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SFKY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bz" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="KFLX" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="IsMZ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsZY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="YPZB" Type="System.Decimal" DbType="Decimal(8,4)" CanBeNull="true" />
      <Column Name="wbm" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ISZZ" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="BM_ZG" Member="ZG" ThisKey="BMDM" OtherKey="BMDM" Type="ZG" />
      <Association Name="BM_RY" Member="RY" ThisKey="BMDM" OtherKey="RYKS" Type="RY" />
      <Association Name="BM_SFXM" Member="SFXM" ThisKey="BMDM" OtherKey="BMDM" Type="SFXM" />
    </Type>
  </Table>
  <Table Name="dbo.ZG" Member="ZG">
    <Type Name="ZG">
      <Column Name="ZGDM" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ZGXM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PYM" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="XB" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="CSRQ" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ZCDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ZYZH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZGLBDM" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="HY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZZMM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MM" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BMDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="GRBH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LXDH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="XL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="JG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SFJY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IMAGE" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BZ" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DZ" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="ZG_JZD" Member="JZD" ThisKey="ZGDM" OtherKey="YS" Type="JZD" />
      <Association Name="ZG_HJD" Member="HJD" ThisKey="ZGDM" OtherKey="HJCZY" Type="HJD" />
      <Association Name="ZG_HJD1" Member="HJD1" ThisKey="ZGDM" OtherKey="YS" Type="HJD" />
      <Association Name="ZG_DQDJH" Member="DQDJH" ThisKey="ZGDM" OtherKey="CZY" Type="DQDJH" />
      <Association Name="BM_ZG" Member="BM" ThisKey="BMDM" OtherKey="BMDM" Type="BM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZYBR" Member="ZYBR">
    <Type Name="ZYBR">
      <Column Name="ZYH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MZDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BAH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YBKH" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="BRXM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="XB" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="CSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HYZK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="CSD_SS" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CSD_XQ" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CSD_Z" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GJ" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mzks" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JSDW" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="ZYBR_RY" Member="RY" ThisKey="ZYH" OtherKey="ZYH" Type="RY" />
      <Association Name="ZYBR_WyNhRegister" Member="WyNhRegister" ThisKey="ZYH" OtherKey="Zyh" Type="WyNhRegister" />
      <Association Name="ZYBR_WyNhFeeList" Member="WyNhFeeList" ThisKey="ZYH" OtherKey="Zyh" Type="WyNhFeeList" />
      <Association Name="ZYBR_JZD" Member="JZD" ThisKey="ZYH" OtherKey="ZYH" Type="JZD" />
      <Association Name="ZYBR_CY" Member="CY" ThisKey="ZYH" OtherKey="ZYH" Type="CY" />
    </Type>
  </Table>
  <Table Name="dbo.RY" Member="RY">
    <Type Name="RY">
      <Column Name="RYH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ZYH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RYKS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ZYBRLX" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RYYJJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="BJX" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="YJKZJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="JZZJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="RYRQ" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CYRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RYQKDM" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="QFZJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="XJJFZJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CWFZJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CYBJJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="YE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="BXJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="YS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CZY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ZT" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ZF" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RYCH" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="YBBM" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="YLFKFSDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KSDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ycy" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="REGCARD_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="YCYRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HZ_HZZH" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="RegID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="JZZJE_YS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="HZ_REG" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JBSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FLAG" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BudgetDay" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="RY_BASY" Member="BASY" ThisKey="RYH" OtherKey="RYH" Type="BASY" Cardinality="One" />
      <Association Name="BM_RY" Member="BM" ThisKey="RYKS" OtherKey="BMDM" Type="BM" IsForeignKey="true" />
      <Association Name="ZYBR_RY" Member="ZYBR" ThisKey="ZYH" OtherKey="ZYH" Type="ZYBR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BASY" Member="BASY">
    <Type Name="BASY">
      <Column Name="RYH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GZDW_DZ" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="GZDW_DH" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="GZDW_YZBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HK_DZ" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="HK_YZBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LXR_XM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LXR_GX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LXR_DZ" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="LXR_DH" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="MZZD_ICD" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MZZD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RYZD_ICD" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="RYZD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CYZYZD_ICD" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="CYZYZD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CYZYZD_LX" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MZZD_YS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="nl" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="jsdw" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DBR" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="bscsz" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="kkcd" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cyzyzd_zdyj" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="RY_BASY" Member="RY" ThisKey="RYH" OtherKey="RYH" Type="RY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WyNhRegister" Member="WyNhRegister">
    <Type Name="WyNhRegister">
      <Column Name="NhRegID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrganCode" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="AccountYear" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="CoopMedCode" Type="System.String" DbType="VarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="ExpressionID" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="PatientName" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AiIDNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IllCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IllName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="InDate" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Adke" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="AdLimitDef" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorName" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="PatientID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiagNo" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ExpenseKind" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="LimitIllCode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="IsFail" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Zyh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AreaCode" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="TurnID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FunHrStr" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="WyNhRegister_WyNhBalance" Member="WyNhBalance" ThisKey="NhRegID" OtherKey="NhRegID" Type="WyNhBalance" />
      <Association Name="ZYBR_WyNhRegister" Member="ZYBR" ThisKey="Zyh" OtherKey="ZYH" Type="ZYBR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WyNhHiHosItem" Member="WyNhHiHosItem">
    <Type Name="WyNhHiHosItem">
      <Column Name="OrganId" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ztyear" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HosCode" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HosKind" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="OrgCode" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="OrgFlag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HosItem" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="HosSpec" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="HosType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InKind" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FeeTypeCode" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="FeeTypeName" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="wipeout" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="LimitPrice1" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="LimitPrice2" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="LimitPrice3" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="HosGrade" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WyNhFeeList" Member="WyNhFeeList">
    <Type Name="WyNhFeeList">
      <Column Name="Cfh" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Zyh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HosCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NhCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UseDate" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Num" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Fee" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="OfficeName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Doctor" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FeeNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="ZYBR_WyNhFeeList" Member="ZYBR" ThisKey="Zyh" OtherKey="ZYH" Type="ZYBR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JZD" Member="JZD">
    <Type Name="JZD">
      <Column Name="JZDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RQ" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CZY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="YS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ZYH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KDKS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ZXKS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ZF" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ZFCZY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="HJDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZTJZ_CYFPH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SB_UPLOAD" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="zxys" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="zxrq" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DY" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="YSJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="tdh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lsh" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SFJZ" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="JZD_JZDMX" Member="JZDMX" ThisKey="JZDH" OtherKey="JZDH" Type="JZDMX" />
      <Association Name="ZYBR_JZD" Member="ZYBR" ThisKey="ZYH" OtherKey="ZYH" Type="ZYBR" IsForeignKey="true" />
      <Association Name="ZG_JZD" Member="ZG_jzd_ys" ThisKey="YS" OtherKey="ZGDM" Type="ZG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JZDMX" Member="JZDMX">
    <Type Name="JZDMX">
      <Column Name="JZDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="XH" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SFXMDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DJ" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="JE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="YSJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="YBBX" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DZ" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="YBLB" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="RebateScale" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="yzid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="JZD_JZDMX" Member="JZD" ThisKey="JZDH" OtherKey="JZDH" Type="JZD" IsForeignKey="true" />
      <Association Name="SFXM_JZDMX" Member="SFXM" ThisKey="SFXMDM" OtherKey="SFXMDM" Type="SFXM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HJD" Member="HJD">
    <Type Name="HJD">
      <Column Name="HJDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YFDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MZH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RYH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HJCZY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MZFPH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FYCZY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KDKS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="HJRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FYRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZT" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ZF" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ZFCZY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SHYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BRXM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="JZDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="XB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NL" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="JSDW" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HDR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IsTY" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="FYDJH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SENDBILLNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lsh" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SickType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="jzbz" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="ZG_HJD" Member="ZG_HJCZY" Storage="_ZG" ThisKey="HJCZY" OtherKey="ZGDM" Type="ZG" IsForeignKey="true" />
      <Association Name="ZG_HJD1" Member="ZG_YS" ThisKey="YS" OtherKey="ZGDM" Type="ZG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HJDMX" Member="HJDMX">
    <Type Name="HJDMX">
      <Column Name="HJDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="XH" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YPGGDM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YPDWDM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SL" Type="System.Decimal" DbType="Decimal(13,4) NOT NULL" CanBeNull="false" />
      <Column Name="JE" Type="System.Decimal" DbType="Decimal(13,4) NOT NULL" CanBeNull="false" />
      <Column Name="JDSL" Type="System.Decimal" DbType="Decimal(13,4) NOT NULL" CanBeNull="false" />
      <Column Name="YFRKXH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YFRKDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YSJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="YBBX" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DZ" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="YBLB" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="YTY" Type="System.Decimal" DbType="Decimal(10,4)" CanBeNull="true" />
      <Column Name="TY" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SCSDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YF" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="YL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RebateScale" Type="System.Decimal" DbType="Decimal(7,3)" CanBeNull="true" />
      <Column Name="RKXH" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TYS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ypmc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="yzid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LSJ" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PFJ" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="JJ" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="JIAOZ" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="JYCS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BEIZ" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="YPGG_HJDMX" Member="YPGG" ThisKey="YPGGDM" OtherKey="YPGGDM" Type="YPGG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SFXM" Member="SFXM">
    <Type Name="SFXM">
      <Column Name="SFXMDM" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SFXMMC" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DW" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DJ" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="SFDJ" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="YBBM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="KZBM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PYM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="XMBM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="YJKMDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="EJKMDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BMDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BMMC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SFKY" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="YBLBDM" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DZ" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="bs" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="YBMC" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="HZ_XMBM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="YBBM_2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="InhosPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="lx" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pltx" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="zxdid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="jjlx" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="fbdm" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="wbm" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="nhdj" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ybdj" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="IsPrint" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ZXYQ" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ZYZXYQ" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JJTX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="part" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fit" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ItemKindID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="SFXM_JZDMX" Member="JZDMX" ThisKey="SFXMDM" OtherKey="SFXMDM" Type="JZDMX" />
      <Association Name="SFXM_YP" Member="YP" ThisKey="SFXMDM" OtherKey="sfxmdm" Type="YP" />
      <Association Name="BM_SFXM" Member="BM" ThisKey="BMDM" OtherKey="BMDM" Type="BM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.YP" Member="YP">
    <Type Name="YP">
      <Column Name="YPDM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YPMC" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PYM" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SFJY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="YPSFXMDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="YPKMDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="YPLXDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YPLX" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Med_ZBLB" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YBBM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="OTHERCODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OTHERCODE_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fltx" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="zxdid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="jjlx" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="wbm" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ypzl" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="fbdm" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sfxmdm" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KZMC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="JBMLYP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CFZW" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="JJSM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="XZTS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="YP_YPGG" Member="YPGG" ThisKey="YPDM" OtherKey="YPDM" Type="YPGG" />
      <Association Name="SFXM_YP" Member="SFXM" ThisKey="sfxmdm" OtherKey="SFXMDM" Type="SFXM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.YPGG" Member="YPGG">
    <Type Name="YPGG">
      <Column Name="YPGGDM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YPGGMC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HW" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="YPJXDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ZXDW" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="JCL" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="HL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PZWH" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CF" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ZZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="YPYFDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YPYLDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YPDM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JJ" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ZYSX" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="YBBM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="YBMC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DZ" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="YPBZ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SCSDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="HZ_XMBM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="GHSDM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YBBM_2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SFKY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="zxjl" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="HZ_XMMC" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="MT_CLDW" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MT_CLBZ" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="YPGG_HJDMX" Member="HJDMX" ThisKey="YPGGDM" OtherKey="YPGGDM" Type="HJDMX" />
      <Association Name="YP_YPGG" Member="YP" ThisKey="YPDM" OtherKey="YPDM" Type="YP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CY" Member="CY">
    <Type Name="CY">
      <Column Name="CYXH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ZYH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CYFPH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ksdm" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CYRQ" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HJJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="YJJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="BJJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="QFJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="QF" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ZF" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ZFCZY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BXJE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="QFLBMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="czy" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="zfrq" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HJJE_YS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="fkfs" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="jsdw" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="jbsj" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChildHJJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="CY_CYFP" Member="CYFP" ThisKey="CYXH" OtherKey="CYXH" Type="CYFP" />
      <Association Name="ZYBR_CY" Member="ZYBR" ThisKey="ZYH" OtherKey="ZYH" Type="ZYBR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CYFP" Member="CYFP">
    <Type Name="CYFP">
      <Column Name="CYFPH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CYXH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RQ" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JSDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HJJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="YJJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="BJJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ZF" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CZY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ZYJZ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CZJZ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BXJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ZYH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SQYE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ZTJZ_QSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZTJZ_ZZRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="zfczy" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BQYE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="HJJE_YS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="lsh" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MotherCYFPH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChildHJJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="CYFP_CYFPMX" Member="CYFPMX" ThisKey="CYFPH" OtherKey="CYFPH" Type="CYFPMX" />
      <Association Name="CY_CYFP" Member="CY" ThisKey="CYXH" OtherKey="CYXH" Type="CY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CYFPMX" Member="CYFPMX">
    <Type Name="CYFPMX">
      <Column Name="CYFPH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="XH" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YJKMDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="JE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="YSJE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MotherCYFPH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CYFP_CYFPMX" Member="CYFP" ThisKey="CYFPH" OtherKey="CYFPH" Type="CYFP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DQDJH" Member="DQDJH">
    <Type Name="DQDJH">
      <Column Name="XH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DJLXDM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CZY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CZYXM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KSDJH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JSDJH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DQDJH" Member="DQDJH1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ZG_DQDJH" Member="ZG" ThisKey="CZY" OtherKey="ZGDM" Type="ZG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WyNhBalance" Member="WyNhBalance">
    <Type Name="WyNhBalance">
      <Column Name="BalanceID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NhRegID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsFail" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DayCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Zyh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cyfph" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalFee" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="ReimRangeFee" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="ReimFee" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="HospitalReduction" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="CivilPay" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="ScAmount" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="HospitalCost" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="BeginLimite" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="SpecialIllHospitalCost" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="YearLimite" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="YearTotalReimFee" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="T1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="WyNhRegister_WyNhBalance" Member="WyNhRegister" ThisKey="NhRegID" OtherKey="NhRegID" Type="WyNhRegister" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.getTsByZyh" Method="getTsByZyh" IsComposable="true">
    <Parameter Name="zyh" Type="System.Int32" DbType="Int" />
    <Parameter Name="dt" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
</Database>