#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCMS_Local.LTSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HNXT_interface")]
	public partial class DCNhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DCNhDataContext() : 
				base(global::NCMS_Local.Properties.Settings.Default.HNXT_interfaceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCNhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCNhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCNhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCNhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<p_Illness> p_Illness
		{
			get
			{
				return this.GetTable<p_Illness>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.p_Illness")]
	public partial class p_Illness
	{
		
		private string _OrganID;
		
		private string _IllCode;
		
		private string _IllName;
		
		private string _Spell;
		
		private string _FiveStrokes;
		
		private char _If_Modified;
		
		public p_Illness()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganID", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string OrganID
		{
			get
			{
				return this._OrganID;
			}
			set
			{
				if ((this._OrganID != value))
				{
					this._OrganID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IllCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string IllCode
		{
			get
			{
				return this._IllCode;
			}
			set
			{
				if ((this._IllCode != value))
				{
					this._IllCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IllName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string IllName
		{
			get
			{
				return this._IllName;
			}
			set
			{
				if ((this._IllName != value))
				{
					this._IllName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spell", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Spell
		{
			get
			{
				return this._Spell;
			}
			set
			{
				if ((this._Spell != value))
				{
					this._Spell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiveStrokes", DbType="VarChar(10)")]
		public string FiveStrokes
		{
			get
			{
				return this._FiveStrokes;
			}
			set
			{
				if ((this._FiveStrokes != value))
				{
					this._FiveStrokes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_If_Modified", DbType="Char(1) NOT NULL")]
		public char If_Modified
		{
			get
			{
				return this._If_Modified;
			}
			set
			{
				if ((this._If_Modified != value))
				{
					this._If_Modified = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
